name: DevOps
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  devops:
    name: Test - Github Actions & Integration & SonarCloud Scan & Slack WebHook
    runs-on: windows-latest # macos-latest macos-11 windows-2019 ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-mode
      - name: Slack WebHook
      if: failure()
         uses: 8398a7/action-slack@v3
         with:
          status: ${{ job.status }}
          fields: repo,author,commit,author,workflow, # selectable (default: repo,message)
        env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required