name: CD - Heroku
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_email: "waelwzwz@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "iwvg-devops-wael-louati"
